# def fetch_comparables(parsed_query: dict, selected_columns: list) -> list:
#     sample = [
#         {
#             "project": "Project A",
#             "location": "Baner",
#             "config": "3 BHK",
#             "area_sqft": 1400,
#             "rate_sqft": 10500,
#             "transaction_date": "2024-01-01",
#             "rental_yield": 0.03,
#             "amenities_score": "9/10",
#             "developer_grade": "A",
#             "distance_to_it_hub": 3.5,
#             "safety_score": 8.8,
#         },
#         {
#             "project": "Project B",
#             "location": "Balewadi",
#             "config": "3 BHK",
#             "area_sqft": 1450,
#             "rate_sqft": 10200,
#             "transaction_date": "2024-02-01",
#             "rental_yield": 0.028,
#             "amenities_score": "8/10",
#             "developer_grade": "A",
#             "distance_to_it_hub": 2.5,
#             "safety_score": 8.5,
#         },
#     ]

#     trimmed_rows = []
#     for row in sample:
#         trimmed = {k: row.get(k) for k in selected_columns if k in row}
#         trimmed_rows.append(trimmed)

#     return trimmed_rows

from typing import Dict, List


SAMPLE_ROWS: List[Dict[str, object]] = [
    {
        "project_name": "Project A",
        "project_id": "P-101",
        "developer_name": "Developer One",
        "property_type": "Apartment",
        "property_subtype": "Residential",
        "bhk_type": "3 BHK",
        "unit_number": "A-1203",
        "tower_name": "A",
        "floor_number": 12,
        "possession_status": "Ready",
        "project_status": "Completed",
        "location_name": "Baner",
        "micromarket": "West Pune",
        "submarket": "Baner-Balewadi",
        "city_name": "Pune",
        "state_name": "Maharashtra",
        "pincode": "411045",
        "latitude": 18.559,
        "longitude": 73.786,
        "distance_from_subject_km": 1.8,
        "unit_area_sqft": 1400,
        "unit_area_sqm": 130.06,
        "carpet_area_sqft": 1080,
        "carpet_area_sqm": 100.33,
        "saleable_area_sqft": 1400,
        "builtup_area_sqft": 1240,
        "plot_area_sqm": 6200,
        "fsi_area_sqm": 9400,
        "price_per_sqft": 10500,
        "avg_rate_sqft": 10350,
        "asking_price": 14700000,
        "base_price": 14000000,
        "final_price": 14900000,
        "ticket_size": 14900000,
        "transaction_value": 14600000,
        "transaction_date": "2024-01-01",
        "price_growth_yoy": 0.11,
        "discount_percent": 0.03,
        "rental_yield_percent": 0.032,
        "capital_appreciation_rate": 0.12,
        "irr_percent": 0.14,
        "payback_period_years": 8.1,
        "investment_score": 8.7,
        "amenities_score": 9.1,
        "safety_score": 8.8,
        "walkability_score": 7.4,
        "green_area_score": 7.9,
        "density_score": 6.8,
        "lifestyle_score": 8.6,
        "livability_score": 8.4,
        "distance_to_it_hub": 3.5,
        "distance_to_metro": 2.2,
        "distance_to_highway": 1.4,
        "distance_to_railway": 10.5,
        "travel_time_cbd_min": 28,
        "travel_time_it_hub_min": 14,
        "connectivity_score": 8.2,
        "distance_to_school": 0.9,
        "distance_to_hospital": 1.4,
        "distance_to_mall": 2.0,
        "distance_to_airport": 18.0,
        "distance_to_park": 0.4,
        "social_infra_score": 8.3,
        "developer_rating": 4.4,
        "developer_grade": "A",
        "project_completion_rate": 0.94,
        "delay_history_score": 8.1,
        "construction_quality_score": 8.7,
        "brand_value_score": 8.5,
        "total_units": 320,
        "units_available": 32,
        "units_sold": 288,
        "unsold_units": 32,
        "floor_count": 24,
        "parking_ratio": 1.4,
        "parking_count": 420,
        "unit_mix_score": 8.0,
        "rera_status": "Registered",
        "rera_number": "RERA-PROJ-1001",
        "approval_status": "Approved",
        "land_title_clearance": "Clear",
        "compliance_score": 9.1,
        "litigation_flag": "No",
        "total_cost": 15600000,
        "additional_charges": 650000,
        "maintenance_cost": 5500,
        "stamp_duty_cost": 745000,
        "registration_cost": 30000,
        "cost_efficiency_score": 7.8,
        "upcoming_infra_score": 8.6,
        "metro_impact_score": 8.4,
        "road_widening_impact": 7.0,
        "future_development_index": 8.3,
        "absorption_rate": 24,
        "velocity_index": 8.2,
        "demand_index": 8.5,
        "market_heat_score": 8.1,
        "launch_count": 5,
        "inventory_months": 7,
        "supply_score": 7.2,
        "demand_supply_ratio": 1.4,
        "new_supply_units": 120,
        "sold_to_launched_ratio": 0.81,
        "furnishing_status": "Semi-Furnished",
        "facing_direction": "East",
        "view_type": "Garden",
        "age_of_property": 2,
        "construction_stage": "Completed",
    },
    {
        "project_name": "Project B",
        "project_id": "P-102",
        "developer_name": "Developer Two",
        "property_type": "Apartment",
        "property_subtype": "Residential",
        "bhk_type": "3 BHK",
        "unit_number": "B-0902",
        "tower_name": "B",
        "floor_number": 9,
        "possession_status": "Near Possession",
        "project_status": "Ongoing",
        "location_name": "Balewadi",
        "micromarket": "West Pune",
        "submarket": "Baner-Balewadi",
        "city_name": "Pune",
        "state_name": "Maharashtra",
        "pincode": "411045",
        "latitude": 18.570,
        "longitude": 73.779,
        "distance_from_subject_km": 2.7,
        "unit_area_sqft": 1450,
        "unit_area_sqm": 134.70,
        "carpet_area_sqft": 1105,
        "carpet_area_sqm": 102.65,
        "saleable_area_sqft": 1450,
        "builtup_area_sqft": 1285,
        "plot_area_sqm": 7100,
        "fsi_area_sqm": 10500,
        "price_per_sqft": 10200,
        "avg_rate_sqft": 10080,
        "asking_price": 14800000,
        "base_price": 14300000,
        "final_price": 15000000,
        "ticket_size": 15000000,
        "transaction_value": 14200000,
        "transaction_date": "2024-02-01",
        "price_growth_yoy": 0.09,
        "discount_percent": 0.04,
        "rental_yield_percent": 0.029,
        "capital_appreciation_rate": 0.10,
        "irr_percent": 0.128,
        "payback_period_years": 8.8,
        "investment_score": 8.1,
        "amenities_score": 8.5,
        "safety_score": 8.4,
        "walkability_score": 7.8,
        "green_area_score": 7.1,
        "density_score": 7.0,
        "lifestyle_score": 8.2,
        "livability_score": 8.0,
        "distance_to_it_hub": 2.5,
        "distance_to_metro": 2.9,
        "distance_to_highway": 1.8,
        "distance_to_railway": 11.2,
        "travel_time_cbd_min": 31,
        "travel_time_it_hub_min": 12,
        "connectivity_score": 8.0,
        "distance_to_school": 1.1,
        "distance_to_hospital": 1.8,
        "distance_to_mall": 2.3,
        "distance_to_airport": 19.5,
        "distance_to_park": 0.7,
        "social_infra_score": 8.0,
        "developer_rating": 4.2,
        "developer_grade": "A",
        "project_completion_rate": 0.89,
        "delay_history_score": 7.6,
        "construction_quality_score": 8.3,
        "brand_value_score": 8.2,
        "total_units": 410,
        "units_available": 68,
        "units_sold": 342,
        "unsold_units": 68,
        "floor_count": 28,
        "parking_ratio": 1.3,
        "parking_count": 510,
        "unit_mix_score": 7.8,
        "rera_status": "Registered",
        "rera_number": "RERA-PROJ-1002",
        "approval_status": "Approved",
        "land_title_clearance": "Clear",
        "compliance_score": 8.8,
        "litigation_flag": "No",
        "total_cost": 15850000,
        "additional_charges": 720000,
        "maintenance_cost": 5200,
        "stamp_duty_cost": 750000,
        "registration_cost": 30000,
        "cost_efficiency_score": 7.5,
        "upcoming_infra_score": 8.8,
        "metro_impact_score": 8.1,
        "road_widening_impact": 7.4,
        "future_development_index": 8.5,
        "absorption_rate": 21,
        "velocity_index": 7.9,
        "demand_index": 8.2,
        "market_heat_score": 7.9,
        "launch_count": 6,
        "inventory_months": 9,
        "supply_score": 7.5,
        "demand_supply_ratio": 1.2,
        "new_supply_units": 180,
        "sold_to_launched_ratio": 0.75,
        "furnishing_status": "Unfurnished",
        "facing_direction": "North",
        "view_type": "City",
        "age_of_property": 1,
        "construction_stage": "Finishing",
    },
]


REAL_ESTATE_DOMAINS = {"real_estate"}


def _matches_filters(row: Dict[str, object], filters: Dict[str, object]) -> bool:
    if not filters:
        return True

    location = str(filters.get("location", "")).lower().strip()
    bhk = str(filters.get("bhk", "")).lower().strip()
    property_type = str(filters.get("property_type", "")).lower().strip()

    if location and location not in str(row.get("location_name", "")).lower():
        return False
    if bhk and bhk not in str(row.get("bhk_type", "")).lower():
        return False
    if property_type and property_type not in str(row.get("property_type", "")).lower():
        return False
    return True


def fetch_comparables(parsed_query: dict, selected_columns: list) -> list:
    if parsed_query.get("domain") not in REAL_ESTATE_DOMAINS:
        return []

    rows = []
    for row in SAMPLE_ROWS:
        if _matches_filters(row, parsed_query.get("filters", {})):
            trimmed = {key: row.get(key) for key in selected_columns}
            rows.append(trimmed)

    return rows
